export const color = {
    headerBar: '#ffc226',
    headerText: '#2c3051',
    button: '#ffc226',
    buttonText: 'white',
    border: '#a1a1a1',
    borderNotValid: 'red',
    inputText: '#2c3051',
    placeholderTextColor: '#a1a1a1',
    mainBackgroundColor: '#ededef',
    itemBackgroundColor: 'white',
    infoTextColor: '#6d6d6d',
    subtitleColor: '#6d6d6d',
    seeAllButtonColor: '#d8d8d8',
    seeAllTextColor: '#353535'
}

export const screenName = {
    homeScreen: "HomeScreen",
    listCoursesScreen: "ListCoursesScreen",
    coursesDetailScreen: "CoursesDetailScreen",
    changePasswordScreen: "ChangePasswordScreen",
    settingScreen: "SettingScreen",
    downloadScreen: "DownloadScreen",
    browseScreen: "BrowseScreen",
    searchScreen: "SearchScreen",
    resultScreen: "ResultScreen",
    splashScreen: "SplashScreen",
    loginScreen: "LoginScreen",
    bottomTabScreen: "BottomTabScreen",
    themeSettingScreen: "ThemeSettingScreen",
    profileScreen: "ProfileScreen",
    settingScreen: "SettingScreen",
    signupScreen: "SignUpScreen",
    registerSuccessfullyScreen: "RegisterSuccessfullyScreen",
    forgotPasswordScreen: "ForgotPasswordScreen",
}

export const themes = {
    light: {
        headerBar: '#ffc226',
        headerText: '#2c3051',
        button: '#ffc226',
        buttonText: 'white',
        border: '#a1a1a1',
        inputText: '#2c3051',
        placeholderTextColor: '#a1a1a1',
        mainBackgroundColor: '#ededef',
        itemBackgroundColor: 'white',
        infoTextColor: '#6d6d6d',
        subtitleColor: '#6d6d6d',
        seeAllButtonColor: '#d8d8d8',
        seeAllTextColor: '#353535',
        backgroundBottomBar: 'white',
        activeTintColor: '#ffc226',
        inactiveTintColor: '#6d6d6d',
        lightSeachBar: true,
    },

    dark: {
        headerBar: '#121212',
        headerText: 'white',
        button: '#ffc226',
        buttonText: 'white',
        border: '#a1a1a1',
        inputText: '#2c3051',
        placeholderTextColor: '#a1a1a1',
        mainBackgroundColor: '#121212',
        itemBackgroundColor: '#393e46',
        infoTextColor: '#d6d6d6',
        subtitleColor: '#d6d6d6',
        seeAllButtonColor: '#393e46',
        seeAllTextColor: 'white',
        backgroundBottomBar: '#121212',
        activeTintColor: 'white',
        inactiveTintColor: '#393e46',
        lightSeachBar: false,
    }
}